apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: o2o-staging

resources:
  - ../../base

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: backend
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: "1"
                    memory: 1Gi
    target:
      kind: Deployment
      name: backend

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: admin-web
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: admin-web

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: backend
      spec:
        minReplicas: 1
        maxReplicas: 4
    target:
      kind: HorizontalPodAutoscaler
      name: backend

  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: backend-config
      data:
        NODE_ENV: "staging"
    target:
      kind: ConfigMap
      name: backend-config

  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: o2o
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-staging
      spec:
        tls:
          - hosts:
              - staging-api.o2o.com
              - staging-admin.o2o.com
            secretName: o2o-staging-tls
        rules:
          - host: staging-api.o2o.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: backend
                      port:
                        number: 80
          - host: staging-admin.o2o.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: admin-web
                      port:
                        number: 80
    target:
      kind: Ingress
      name: o2o
