apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: o2o
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
