apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-hpa.yaml
  - admin-web-deployment.yaml
  - ingress.yaml
  - configmap.yaml
  - secret.yaml
  - pdb.yaml
  - networkpolicy.yaml
